### ISSUE TITLE
目前已经添加过的快捷方式不能修改也不能删除

### ISSUE THREAD

**Issue by yuxigu5254** [lulululbj/Direct#1]
https://github.com/user-attachments/assets/9c3ac549-9df5-401b-9c72-6abea191b627

这个是酷安的一个应用页快捷方式coolmarket://com.coolapk.market/apk/com.salt.music，主页搜索出来快捷方式长按查看空白且快捷方式管理页没有显示该快捷方式，没有办法修改和删除

**Comment by lulululbj** [comment]
fixed， https://www.pgyer.com/everywhere
