### ISSUE TITLE
添加新的搜索引擎位置bug

### ISSUE THREAD

**Issue by yuxigu5254** [lulululbj/Direct#2]
添加新的搜索引擎不会排到最后一个，而是会排到第二个位置

https://github.com/user-attachments/assets/d1501362-d4b3-41d8-90d5-91b750feb45e

![iMarkup_20240814_113303](https://github.com/user-attachments/assets/bae4aed3-e546-414f-b07d-b82e359d0acf)

**Comment by lulululbj** [comment]
问题不大，拖动一下位置
